/*
 * This source file was generated by the Gradle 'init' task
 */
package main;

import IA.Test;

public class App {
    public static void main(String[] args) {
        Test test = new Test();
        test.run();
    }
}
