/*
 * This source file was generated by the Gradle 'init' task
 */
package main;

import IA.Test;
public class App {
    
    private static final String FILE_DIR_PATH = "./src/main/java/IA/inputs/";
    public static void main(String[] args) {

        Test test = new Test();
        
        //test.run("");
        int index = 2; // Starting from 0
        test.run(FILE_DIR_PATH + "input" + index + ".ini");

        int iterations = 1;
        System.out.println("Trying HC with " + iterations + " iterations");
        while (iterations > 0) {
            iterations--;
            System.out.print("iteration " + iterations + ": ");
  
            test.provaHC();
            // provaSA();
        }
    }
    
}
