/*
 * This source file was generated by the Gradle 'init' task
 */
package main;

public class App {

    public static void main(String[] args) {

        // Test.printInitialConnection();
        // Test.printStateFromFiles();
        // Test.printStateFromFile(1);

        Test.provaHC(1);
    }

}
